# Generated by Django 2.2.14 on 2020-10-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('henna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.FileField(upload_to='images/gallery_images'),
        ),
        migrations.AlterField(
            model_name='mainslideimage',
            name='image',
            field=models.FileField(upload_to='images/main_slide_images'),
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='image',
            field=models.FileField(upload_to='images/page_images'),
        ),
    ]
