# Generated by Django 2.2.14 on 2020-10-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('henna', '0002_auto_20201022_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='package',
            field=models.CharField(choices=[('cb', 'Classic Bridal'), ('eb', 'Elegant Bridal'), ('rb', 'Royal Bridal'), ('sb1', 'Star Bridal 1'), ('sb2', 'Star Bridal 2')], default='cb', max_length=2, null=True),
        ),
    ]
