# Generated by Django 2.2.14 on 2020-10-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('henna', '0002_auto_20201026_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.FileField(upload_to='gallery_images'),
        ),
        migrations.AlterField(
            model_name='mainslideimage',
            name='image',
            field=models.FileField(upload_to='main_slide_images'),
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='image',
            field=models.FileField(upload_to='page_images'),
        ),
    ]
