# Generated by Django 2.2.14 on 2020-10-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('henna', '0003_auto_20201022_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='images/gallery_images'),
        ),
    ]
