# Generated by Django 2.2.14 on 2020-10-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('henna', '0004_auto_20201025_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
